version: '1.0'
services:
  task-service:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      - PORT=4000
    ports:
      - 4000:4000
    volumes:
      - ./src:/usr/src/app/src 
  mongodb:
    image: mongo:latest
    container_name: task-service
    ports:
      - 27017:27017
